project:
  type: book        
  output-dir: docs
  execute-dir: project
book:
  title: "Notes on Sutton & Barto"
  author: "Julian Bitterlich"
  repo-url: https://github.com/julxi/notes_and_solutions_reinforcement_learning
  chapters:
    - index.qmd
    - chapters/01-intro.qmd
    - chapters/02-multi-armed-bandits.qmd
    - chapters/03-finite-markov-decision-processes.qmd
    - chapters/04-dynamic-programming.qmd
    - chapters/05-monte-carlo-methods.qmd
    - chapters/06-temporal-difference-learning.qmd
bibliography: references.bib
format:
  html:
    page-layout: article
    respect-user-color-scheme: true
    theme:
      dark: [darkly, theme-dark.scss]
      light: flatly
    highlight-style: oblivion
    css: styles.css
    number-sections: true
    code-fold: true
    lightbox: true

execute: 
  cache: true
filters:
  - diagram



